import type { Address } from "viem";

import { FUNDED_DEMO_CONTROLLER_ADDRESS } from "config/funded";

import type {
  FundedDashboardData,
  FundedFeatureItem,
  FundedGuideStep,
  FundedMarketGroup,
  FundedTrackDefinition,
} from "./funded-types";

export const FUNDED_TRACKS: FundedTrackDefinition[] = [
  {
    id: "entry",
    eyebrow: "Starter ladder",
    label: "Entry Track",
    description: "Lower deposit, slower progression, and broader room to validate the funded flow before account switching lands.",
    depositUsd: 100,
    startsAtUsd: 500,
    levelsToTop: 6,
    levels: [
      {
        id: "spark",
        name: "Spark",
        accountSizeUsd: 500,
        depositUsd: 100,
        profitTargetUsd: 75,
        pointsTarget: 100,
        maxDrawdownPct: 20,
        accentColor: "#94a3b8",
      },
      {
        id: "surge",
        name: "Surge",
        accountSizeUsd: 1250,
        depositUsd: 150,
        profitTargetUsd: 187.5,
        pointsTarget: 100,
        maxDrawdownPct: 15,
        accentColor: "#60a5fa",
      },
      {
        id: "bronze",
        name: "Bronze",
        accountSizeUsd: 2500,
        depositUsd: 175,
        profitTargetUsd: 375,
        pointsTarget: 100,
        maxDrawdownPct: 15,
        accentColor: "#cd7f32",
      },
      {
        id: "silver",
        name: "Silver",
        accountSizeUsd: 5000,
        depositUsd: 350,
        profitTargetUsd: 750,
        pointsTarget: 100,
        maxDrawdownPct: 12,
        accentColor: "#9ca3af",
      },
      {
        id: "gold",
        name: "Gold",
        accountSizeUsd: 7500,
        depositUsd: 350,
        profitTargetUsd: 1125,
        pointsTarget: 100,
        maxDrawdownPct: 10,
        accentColor: "#f59e0b",
      },
      {
        id: "platinum",
        name: "Platinum",
        accountSizeUsd: 10000,
        depositUsd: 500,
        profitTargetUsd: 1500,
        pointsTarget: 100,
        maxDrawdownPct: 10,
        accentColor: "#d946ef",
      },
    ],
  },
  {
    id: "pro",
    eyebrow: "Faster ladder",
    label: "Pro Track",
    description: "Bigger starting sizes with fewer level jumps. This route stays preview-only until funded mode switching is implemented.",
    depositUsd: 500,
    startsAtUsd: 2500,
    levelsToTop: 4,
    badgeLabel: "Faster",
    levels: [
      {
        id: "bronze",
        name: "Bronze",
        accountSizeUsd: 2500,
        depositUsd: 500,
        profitTargetUsd: 375,
        pointsTarget: 100,
        maxDrawdownPct: 20,
        accentColor: "#cd7f32",
      },
      {
        id: "silver",
        name: "Silver",
        accountSizeUsd: 5000,
        depositUsd: 500,
        profitTargetUsd: 750,
        pointsTarget: 100,
        maxDrawdownPct: 15,
        accentColor: "#9ca3af",
      },
      {
        id: "gold",
        name: "Gold",
        accountSizeUsd: 7500,
        depositUsd: 500,
        profitTargetUsd: 1125,
        pointsTarget: 100,
        maxDrawdownPct: 12,
        accentColor: "#f59e0b",
      },
      {
        id: "platinum",
        name: "Platinum",
        accountSizeUsd: 10000,
        depositUsd: 500,
        profitTargetUsd: 1500,
        pointsTarget: 100,
        maxDrawdownPct: 12,
        accentColor: "#d946ef",
      },
    ],
  },
];

export const FUNDED_FEATURES: FundedFeatureItem[] = [
  { icon: "🚫", title: "No KYC", description: "Stay anonymous. No identity verification at any point." },
  { icon: "📰", title: "News Trading Allowed", description: "Trade high-impact news events freely." },
  { icon: "🤖", title: "Algos & Bots Welcome", description: "Automated strategies are fully permitted." },
  { icon: "🌙", title: "No Overnight Fee", description: "Hold trades as long as you want, zero extra cost." },
  { icon: "📉", title: "No Trailing Drawdown", description: "Fixed drawdown only. Your limit never moves against you." },
  { icon: "⚖️", title: "Hedging Allowed", description: "Hedge freely across positions and accounts." },
  { icon: "📂", title: "Multiple Accounts", description: "Run multiple funded accounts simultaneously." },
  { icon: "⛓️", title: "100% On-Chain Rules", description: "Every challenge rule is enforced by contracts, not a support queue." },
  { icon: "⚡", title: "Instant Payouts", description: "Payout narrative stays visible while setup remains preview-only in this app shell." },
];

export const FUNDED_MARKET_GROUPS: FundedMarketGroup[] = [
  { icon: "₿", title: "Crypto", badgeLabel: "100+ pairs", symbols: ["BTC", "ETH", "SOL", "DOGE", "XRP", "AVAX"] },
  { icon: "🪙", title: "Metals", symbols: ["Gold", "Silver"] },
  { icon: "📈", title: "Indices", symbols: ["S&P 500", "NASDAQ 100"] },
  { icon: "🏢", title: "Stocks", symbols: ["NVDA", "GOOGL", "TSLA"] },
];

export const FUNDED_GUIDE_STEPS: FundedGuideStep[] = [
  { title: "Choose a track", description: "Entry and Pro define the starting deposit, first account size, and how quickly the ladder scales." },
  { title: "Lock a controller", description: "The real funded flow will mint or attach a funded controller account. This preview keeps that action informational." },
  { title: "Trade on GMX", description: "Normal GMX trading remains the default. Full funded mode switching stays deferred until the provider integration is approved." },
  { title: "Review challenge stats", description: "The funded dashboard already supports a direct controller lookup and can fall back to typed preview data." },
];

export function getFundedDashboardDemo(
  controllerAddress?: Address,
  options?: { degraded?: boolean; announcement?: string }
): FundedDashboardData {
  return {
    meta: {
      source: "demo",
      controllerAddress: controllerAddress ?? FUNDED_DEMO_CONTROLLER_ADDRESS,
      readonly: true,
      degraded: options?.degraded ?? false,
      lastUpdatedLabel: "Preview dataset refreshed 5 minutes ago",
      announcement: options?.announcement ?? undefined,
    },
    summary: {
      trackLabel: "Entry Track",
      levelLabel: "Iron",
      accountSizeUsd: 30,
      collateralUsd: 0,
      drawdownLimitPct: 3,
      currentPnlUsd: -3.58,
      currentPnlPct: -11.93,
      maxDrawdownPct: 11.93,
      minProfitTargetUsd: 4.5,
      totalVolumeUsd: 584.61,
      currentPoints: 0,
      pointsRequired: 100,
      remainingHours: 0,
      status: "On Deck",
    },
    pnlSeries: [
      { label: "Mar 18", value: -19.5 },
      { label: "Mar 19", value: -14.2 },
      { label: "Mar 20", value: -10.8 },
      { label: "Mar 21", value: -7.6 },
      { label: "Mar 22", value: -5.4 },
      { label: "Mar 23", value: -4.1 },
      { label: "Mar 24", value: -3.58 },
    ],
    volumeSeries: [
      { label: "Mar 18", value: 584.61 },
      { label: "Mar 19", value: 0 },
      { label: "Mar 20", value: 0 },
      { label: "Mar 21", value: 0 },
      { label: "Mar 22", value: 0 },
      { label: "Mar 23", value: 0 },
      { label: "Mar 24", value: 0 },
    ],
    modifiers: [
      { label: "Sharpe bonus", value: "0.00", tone: "default" },
      { label: "Calmar bonus", value: "0.00", tone: "default" },
      { label: "Consistency", value: "0.00", tone: "default" },
      { label: "Combined multiplier", value: "1.00x", tone: "positive" },
    ],
    nextSteps: [
      "Enable the funded backend URL to replace preview data on this route.",
      "Approve full funded mode switching before wiring controller setup and funded trading actions.",
    ],
    recentTrades: [
      {
        id: "1",
        timestampLabel: "03/25/2026 00:05:02 AM",
        symbol: "ETH",
        direction: "Short",
        sizeUsd: 290.6173,
        pnlUsd: 0,
        points: 0,
      },
      {
        id: "2",
        timestampLabel: "03/24/2026 10:30:00 AM",
        symbol: "ETH",
        direction: "Long",
        sizeUsd: 293.9901,
        pnlUsd: 0,
        points: 0,
      },
    ],
    journeyMeta: {
      challengeName: "Iron",
      challengeType: "DEVTEST",
      levelNum: 3,
      totalLevels: 3,
      startDateLabel: "Mar 24, 2026",
      daysIn: 69,
    },
    overviewExtras: {
      activityTimerStatus: "Expired",
      activityTimerHelper: "Resets on next trade",
      pointsTrend: "Trending stable",
      snapshotAmountUsd: 26.42,
      snapshotDateLabel: "Mar 24, 00:00 UTC",
      tradingFrequencyPerDay: 0.0,
    },
    performanceStats: {
      sharpeRatio: 0.0,
      sharpeLabel: "Below average",
      calmarRatio: 0.0,
      calmarLabel: "Below average",
      gainToPain: 0.0,
      gainToPainLabel: "Steady",
      consistency: 0.0,
      consistencyLabel: "Variable",
      combinedModifier: 1.0,
      sessions: 3,
      avgTradeSizeUsd: 292.3,
      winLossRatio: 100,
      commissionPaid: 0,
      activityPenalty: 0,
      fundsTxFee: 0,
      availableProfit: 0,
      availableCollateral: 0,
      assetDistribution: [{ symbol: "PERP_ETH", pct: 100 }],
      peerPerformance: "Above Average",
      peerPerformanceTone: "positive",
      peerVolume: "Below Average",
      peerVolumeTone: "negative",
      peerDuration: "Faster",
      peerDurationTone: "positive",
      dailyPnlSeries: [
        { label: "Mar 18", value: -19.5 },
        { label: "Mar 19", value: -0.8 },
        { label: "Mar 24", value: -3.58 },
      ],
    },
    levelUpData: {
      challengeDurationDays: 0.6,
      availableProfitUsd: 0,
      availableCollateralUsd: 0,
      totalWithdrawnUsd: 0,
      levelEndedTitle: "Iron ended. Restart Iron or try Nickel.",
      levelEndedSubtitle:
        "This level concluded without promotion. Withdraw available collateral or restart to try again.",
      nextLevel: {
        levelName: "Nickel",
        advanceLabel: "IRON → NICKEL",
        description: "Your account hit its drawdown limit. Give it another try when you feel ready!",
        accountSizeUsd: 20,
        collateralUsd: 1,
        drawdownLimitPct: 4,
        requiredCollateralUsd: 1,
        availableFundsUsd: 0,
        netDepositRequired: 1,
      },
    },
  };
}
